language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r zoomEdgar-webservice *
  - mkdir -p deploy
  - mv zoomEdgar-webservice.zip deploy/zoomEdgar-webservice.zip

  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.war before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/zoomEdgar-webservice.zip
